name: lint

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install pip
        run: uv python install

      - name: Install Hatch
        run: uv tool install hatch

      - name: Create Hatch virtual env
        run: hatch env create

      - name: Lint with Ruff
        run: hatch run uvx ruff check

      - name: Lint with Pyright
        run: hatch run uvx pyright
