name: pyright_check
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Create virtual environment with hatch
        run: |
          hatch env create

      - name: Run Pyright using hatch
        run: |
          hatch run pyright
