name: releases

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  setup_ubuntu_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (x64)
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: "x64"

      - name: Install Hatch
        run: pip install hatch

      - name: Create Hatch virtual environment for x86_64-linux
        run: hatch env create x86_64-unknown-linux-gnu

      - name: Build Release
        run: hatch run py_project_dev_tools make_exe_release_ci_cd --os_arch_line "x86_64-unknown-linux-gnu"

  setup_ubuntu_aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (arm64)
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: "arm64"

      - name: Install Hatch
        run: pip install hatch

      - name: Create Hatch virtual environment for aarch64-linux
        run: hatch env create aarch64-unknown-linux-gnu

      - name: Build Release
        run: hatch run py_project_dev_tools make_exe_release_ci_cd --os_arch_line "aarch64-unknown-linux-gnu"

  setup_windows_x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (x64)
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: "x64"

      - name: Install Hatch
        run: pip install hatch

      - name: Create Hatch virtual environment for x86_64-windows
        run: hatch env create x86_64-pc-windows-msvc

      - name: Build Release
        run: hatch run py_project_dev_tools make_exe_release_ci_cd --os_arch_line "x86_64-pc-windows-msvc"

  setup_windows_i686:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (x86)
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: "x86"

      - name: Install Hatch
        run: pip install hatch

      - name: Create Hatch virtual environment for i686-windows
        run: hatch env create i686-pc-windows-msvc

      - name: Build Release
        run: hatch run py_project_dev_tools make_exe_release_ci_cd --os_arch_line "i686-pc-windows-msvc"

  setup_wheels_and_source_distributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (x64)
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: "x64"

      - name: Install Hatch
        run: pip install hatch

      - name: Build Wheels and Source Distributions
        run: hatch build

      - name: Twine check
        run: hatch run uvx twine check dist/*

      # - name: Publish Wheels and Source Distributions
      #   run: hatch publish --repo "test" --user "__token__" --auth "${{ secrets.PYPI_PASSWORD }}"

      - name: Publish Wheels and Source Distributions
        run: hatch run uvx twine upload --repository-url https://test.pypi.org/legacy/ dist/* --user "__token__" --password "${{ secrets.PYPI_PASSWORD }}"