name: releases

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, x86, arm64, armv7, arm32]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Hatch
        run: pip install hatch

      - name: Create Hatch virtual environment
        run: hatch env create ${{ matrix.os }}_${{ matrix.arch }}

      - name: Build Release
        run: hatch run py_project_dev_tools make_exe_release_ci_cd
